const $=id=>document.getElementById(id), money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(+v||0), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])), uid=p=>p+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);let db,settings,auth,products=[],clients=[],budgets=[],contracts=[],editingProduct=null,editingClient=null,budgetItems=[{description:'',qty:1,unit:0}],editingBudget=null,editingContract=null;const STORES=['settings','auth','clients','products','budgets','contracts'];
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open('orcafacil_pro_db',2);r.onupgradeneeded=e=>STORES.forEach(s=>{if(!e.target.result.objectStoreNames.contains(s))e.target.result.createObjectStore(s,{keyPath:'id'})});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function st(n,m='readonly'){return db.transaction(n,m).objectStore(n)}function all(n){return new Promise((res,rej)=>{let r=st(n).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}function get(n,id){return new Promise((res,rej)=>{let r=st(n).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}function put(n,o){return new Promise((res,rej)=>{let r=st(n,'readwrite').put(o);r.onsuccess=()=>res(o);r.onerror=()=>rej(r.error)})}function del(n,id){return new Promise((res,rej)=>{let r=st(n,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}async function hash(v){let h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return [...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}function toast(t){$('toast').textContent=t;$('toast').classList.add('on');setTimeout(()=>$('toast').classList.remove('on'),1800)}
async function init(){
  db=await openDB();
  settings=await get('settings','main')||{id:'main',companyName:'',companyDoc:'',companyOwner:'',companyPhone:'',companyEmail:'',companyAddress:'',companyCity:'',companyLogo:'',companySlogan:'',pixKey:'',budgetPrefix:'ORC',budgetSeq:1,contractPrefix:'CTR',contractSeq:1};
  settings={companyLogo:'',companySlogan:'',pixKey:'',budgetPrefix:'ORC',budgetSeq:1,contractPrefix:'CTR',contractSeq:1,...settings};
  await put('settings',settings);
  auth=await get('auth','admin');
  await refresh();
  bindNav(); fillSettings(); syncAdminSide(); applyLogoUI();
  if(auth){$('setup').classList.add('hide');$('enter').classList.remove('hide');$('hello').textContent='Olá, '+(auth.name||'Administrador')}
  else{$('setup').classList.remove('hide');$('enter').classList.add('hide')}
}
async function refresh(){
  products=(await all('products')).sort((a,b)=>(a.name||'').localeCompare(b.name||''));
  clients=(await all('clients')).sort((a,b)=>(a.name||'').localeCompare(b.name||''));
  budgets=(await all('budgets')).sort((a,b)=>new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt));
  contracts=(await all('contracts')).sort((a,b)=>new Date(b.updatedAt||b.createdAt)-new Date(a.updatedAt||a.createdAt));
  renderAll();
}
function bindNav(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.v))}function go(v){updatePageMeta(v);document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id===v));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('on',x.dataset.v===v));window.scrollTo(0,0)}
async function createAccess(){let n=$('setupName').value.trim(),p=$('setupPin').value;if(!n||!/^[0-9]{4,8}$/.test(p))return toast('Informe nome e PIN de 4 a 8 números');auth={id:'admin',name:n,pinHash:await hash(p)};await put('auth',auth);$('setup').classList.add('hide');$('enter').classList.remove('hide');$('hello').textContent='Olá, '+n;syncAdminSide();toast('Acesso criado')}async function doLogin(){if(await hash($('loginPin').value)!==auth.pinHash)return toast('PIN incorreto');$('login').classList.add('hide');$('loginPin').value=''}function logout(){$('login').classList.remove('hide');$('loginPin').value=''}
function renderAll(){
  $('nProd').textContent=products.length;
  $('nCli').textContent=clients.length;
  $('nOrc').textContent=budgets.length;
  if($('nValue'))$('nValue').textContent=money(budgets.reduce((sum,b)=>sum+(+b.total||0),0));
  $('orcNum').textContent=(settings.budgetPrefix||'ORC')+'-'+String(settings.budgetSeq||1).padStart(4,'0');
  if($('contractNum'))$('contractNum').textContent=(settings.contractPrefix||'CTR')+'-'+String(settings.contractSeq||1).padStart(4,'0');
  renderProducts(); renderClients(); renderBudgetItems(); applyLogoUI();
  let co='<option value="">Selecione...</option>'+clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');
  $('budgetClient').innerHTML=co;
  let po='<option value="">Produto/serviço cadastrado...</option>'+products.filter(p=>p.active!==false).map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)}</option>`).join('');
  $('catalogPick').innerHTML=po;
  let bo='<option value="">Selecione...</option>'+budgets.map(b=>`<option value="${b.id}">${esc(b.number)} — ${esc(b.client?.name||'Cliente')} — ${money(b.total)}</option>`).join('');
  $('contractBudget').innerHTML=bo;
  $('budgetList').innerHTML=budgets.length?budgets.map(b=>`<div class="item historyItem"><div><div class="row"><b>${esc(b.number)} — ${esc(b.client?.name||'Cliente')}</b><span class="statusPill">${esc(b.status||'Rascunho')}</span></div><small>${money(b.total)} • ${new Date(b.createdAt||Date.now()).toLocaleDateString('pt-BR')}</small></div><div class="row historyActions"><select class="miniSelect" onchange="updateBudgetStatus('${b.id}',this.value)"><option ${b.status==='Rascunho'?'selected':''}>Rascunho</option><option ${b.status==='Enviado'?'selected':''}>Enviado</option><option ${b.status==='Aprovado'?'selected':''}>Aprovado</option><option ${b.status==='Recusado'?'selected':''}>Recusado</option></select><button class="btn soft" onclick="loadBudget('${b.id}')">Abrir</button><button class="btn soft" onclick="duplicateBudget('${b.id}')">Duplicar</button><button class="btn green" onclick="contractFrom('${b.id}')">Contrato</button></div></div>`).join(''):'<span class="muted">Nenhum orçamento salvo.</span>';
  if($('recentBudgets'))$('recentBudgets').innerHTML=budgets.slice(0,4).map(b=>`<div class="miniRecent"><div><b>${esc(b.number)}</b><small>${esc(b.client?.name||'Cliente')}</small></div><strong>${money(b.total)}</strong></div>`).join('')||'<span class="muted">Seus orçamentos recentes aparecerão aqui.</span>';
  renderContracts();
}
function clearProduct(){editingProduct=null;['pName','pCode','pCat','pPrice','pCost','pStock','pDesc'].forEach(i=>$(i).value='');$('pType').value='Produto';$('pUnit').value='un'}async function saveProduct(){let name=$('pName').value.trim();if(!name)return toast('Informe o nome');let o={id:editingProduct||uid('prd'),type:$('pType').value,name,code:$('pCode').value.trim(),category:$('pCat').value.trim(),unit:$('pUnit').value,price:+$('pPrice').value||0,cost:+$('pCost').value||0,stock:$('pStock').value===''?null:+$('pStock').value,description:$('pDesc').value.trim(),active:true,updatedAt:new Date().toISOString()};await put('products',o);clearProduct();await refresh();toast('Produto/serviço salvo')}function renderProducts(){if(!$('productList'))return;let q=($('prodSearch')?.value||'').toLowerCase(),a=products.filter(p=>[p.name,p.code,p.category].join(' ').toLowerCase().includes(q));$('productList').innerHTML=a.length?a.map(p=>`<div class="item"><div><b>${esc(p.name)}</b><small>${esc(p.type||'Produto')} • ${esc(p.category||'Sem categoria')} • ${money(p.price)}${p.stock!=null?' • Estoque: '+p.stock:''}</small></div><div class="row"><button class="btn green" onclick="useProduct('${p.id}')">Usar</button><button class="btn soft" onclick="editProduct('${p.id}')">Editar</button><button class="btn danger" onclick="deleteProduct('${p.id}')">Excluir</button></div></div>`).join(''):'<span class="muted">Nenhum produto/serviço cadastrado.</span>'}function editProduct(id){let p=products.find(x=>x.id===id);if(!p)return;editingProduct=id;$('pType').value=p.type||'Produto';$('pName').value=p.name||'';$('pCode').value=p.code||'';$('pCat').value=p.category||'';$('pUnit').value=p.unit||'un';$('pPrice').value=p.price||0;$('pCost').value=p.cost||0;$('pStock').value=p.stock??'';$('pDesc').value=p.description||'';go('produtos')}async function deleteProduct(id){if(confirm('Excluir este produto/serviço?')){await del('products',id);await refresh()}}function useProduct(id){go('orcamento');$('catalogPick').value=id;addCatalog()}
function clearClient(){editingClient=null;['cName','cDoc','cPhone','cEmail','cAddress'].forEach(i=>$(i).value='')}async function saveClient(){let name=$('cName').value.trim();if(!name)return toast('Informe o nome do cliente');await put('clients',{id:editingClient||uid('cli'),name,doc:$('cDoc').value.trim(),phone:$('cPhone').value.trim(),email:$('cEmail').value.trim(),address:$('cAddress').value.trim(),updatedAt:new Date().toISOString()});clearClient();await refresh();toast('Cliente salvo')}function renderClients(){$('clientList').innerHTML=clients.length?clients.map(c=>`<div class="item"><div><b>${esc(c.name)}</b><small>${esc(c.phone||'Sem telefone')} • ${esc(c.doc||'Sem documento')}</small></div><div class="row"><button class="btn soft" onclick="editClient('${c.id}')">Editar</button><button class="btn danger" onclick="deleteClient('${c.id}')">Excluir</button></div></div>`).join(''):'<span class="muted">Nenhum cliente cadastrado.</span>'}function editClient(id){let c=clients.find(x=>x.id===id);editingClient=id;$('cName').value=c.name||'';$('cDoc').value=c.doc||'';$('cPhone').value=c.phone||'';$('cEmail').value=c.email||'';$('cAddress').value=c.address||'';go('clientes')}async function deleteClient(id){if(confirm('Excluir cliente?')){await del('clients',id);await refresh()}}
